<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>tripleo.elijah</groupId>
	<artifactId>elevated-potential</artifactId>
	<packaging>pom</packaging>
	<version>2024.elevated-potential.25-11</version>
	<name>elevated-potential</name>
	<url>http://github.com/elijah-lang/elevated-potential</url>

	<properties>
		<!-- <project.build.outputTimestamp>1</project.build.outputTimestamp> -->

		<java.version>17</java.version>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<downloadSources>true</downloadSources>

		<guava.version>33.5.0-jre</guava.version>

		<maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>

		<jdeferred.version>2.0.0</jdeferred.version>

		<!--
		<kotlin.version>1.9.22</kotlin.version>

		<org.eclipse.xtend.lib.version>2.31.0.M3</org.eclipse.xtend.lib.version>
		<xtend-maven-plugin.version>2.31.0.M3</xtend-maven-plugin.version>
		-->
	</properties>

	<modules>
		<module>./annabeth</module>
		<module>./elevated-potential.base.impl</module>
		<module>./elevated-potential.core.api</module>
		<module>./elevated-potential.core.impl</module>
		<module>./xxx-elijah-core-api</module>
	</modules>

	<dependencies>

		<dependency>
			<groupId>com.github.elijah-tng</groupId>
			<artifactId>ghel-model-status</artifactId>
			<version>5dd4c4c71f</version>
		</dependency>

		<dependency>
			<groupId>com.github.elijah-team.radical-paradox</groupId>
			<artifactId>annotation-processing</artifactId>
			<version>0caa8de714</version>
		</dependency>
		<dependency>
			<groupId>com.github.elijah-team.radical-paradox</groupId>
			<artifactId>annotations-mustache</artifactId>
			<version>0caa8de714</version>
		</dependency>

		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr-runtime</artifactId>
			<version>3.5.3</version>
		</dependency>

		<dependency>
			<groupId>io.smallrye.reactive</groupId>
			<artifactId>mutiny</artifactId>
			<version>2.8.0</version>
		</dependency>


		<dependency>
			<groupId>org.clojure</groupId>
			<artifactId>clojure</artifactId>
			<version>1.12.3</version>
		</dependency>


		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>5.20.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.gitlab.tripleo1</groupId>
			<artifactId>buffers</artifactId>
			<version>3038ff102c</version>
		</dependency>

		<dependency>
			<groupId>com.gitlab.Tripleo</groupId>
			<artifactId>range</artifactId>
			<version>0.0.3b</version>
		</dependency>

		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.3.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>org.eclipse.jdt.annotation</artifactId>
			<version>2.3.100</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.19.0</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.1.0-alpha1</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.1.0-alpha1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.github.spotbugs</groupId>
			<artifactId>spotbugs-annotations</artifactId>
			<version>4.9.3</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>${guava.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.reactivex.rxjava3</groupId>
			<artifactId>rxjava</artifactId>
			<version>3.1.10</version>
		</dependency>

		<dependency>
			<groupId>org.reactivestreams</groupId>
			<artifactId>reactive-streams</artifactId>
			<version>1.0.4</version>
		</dependency>

		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.19.0</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.42</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jdeferred.v2</groupId>
			<artifactId>jdeferred-core</artifactId>
			<version>2.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.jetbrains</groupId>
			<artifactId>annotations</artifactId>
			<version>26.0.2-1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.google.auto.service</groupId>
			<artifactId>auto-service-annotations</artifactId>
			<version>1.1.1</version>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.jctools</groupId>
			<artifactId>jctools-core</artifactId>
			<version>4.0.5</version>
		</dependency>

		<dependency>
			<groupId>org.checkerframework</groupId>
			<artifactId>checker-qual</artifactId>
			<version>3.52.1</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
				<executions>
					<execution>
						<id>default-compile</id>
						<phase>none</phase>
					</execution>
					<execution>
						<id>default-testCompile</id>
						<phase>none</phase>
					</execution>
					<execution>
						<id>compile</id>
						<phase>compile</phase>
						<goals>
							<goal>compile</goal>
						</goals>
					</execution>
					<execution>
						<id>testCompile</id>
						<phase>test-compile</phase>
						<goals>
							<goal>testCompile</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
					<release>17</release>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<!--
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-checkstyle-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<configLocation>checkstyle.xml</configLocation>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>checkstyle</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jdepend-maven-plugin</artifactId>
				<version>2.1</version>
			</plugin>
		</plugins>
	</reporting>
	-->
</project>
