<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>tripleo.elijah</groupId>
		<artifactId>elevated-potential</artifactId>
		<version>2024.elevated-potential.25-11</version>
	</parent>

	<artifactId>elevated-potential-core-api-xxx</artifactId>
	<version>2024.elevated-potential.25-11</version>
	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.github.elijah-tng</groupId>
			<artifactId>cegont-upper</artifactId>
			<version>2025.04.21</version>
		</dependency>
		<!--
		<dependency>
			<groupId>tripleo.elijah</groupId>
			<artifactId>elijah-cegont-upper</artifactId>
			<version>2025.04.21</version>
		</dependency>
		-->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>tripleo.elijah</groupId>
			<artifactId>elevated-potential-core-api</artifactId>
			<version>2024.elevated-potential.25-11</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.6.1</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>add-source</goal>
						</goals>
						<configuration>
							<sources>
								<source>../xxx-model-status/src/main/java</source>
								<source>../xxx-annotations/src/main/java</source>

<!--
								<source>./dlog/src/main/java</source>
-->
								<source>./elijah-core-api/src/main/java</source>
								<source>./src/main/java</source>
								<source>./elijah-ek/src/main/java</source>
								<source>./elijah-nextgen-outputstatement/src/main/java</source>
								<source>./elijah-stateful/src/main/java</source>
								<source>./elijah-util/src/main/java</source>
								<source>./tripleo-reactive/src/main/java</source>
								<source>./tripleo-small/src/main/java</source>
							</sources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
</project>
